### ISSUE TITLE
What UI Theme is recommended

### ISSUE THREAD

**Issue by mikeerickson** [polymoon/pure-dark-syntax#1]
Hey There

I am trying out `pure-syntax` with Atom and it looks good.  However, since it is only syntax, curious what UI Theme you are using?

Trying to "match"

![image](https://cloud.githubusercontent.com/assets/183153/22406696/6ad0cc36-e60c-11e6-8126-86346879d6fe.png)

**Comment by pfist** [comment]
I currently use One Dark, which comes with Atom.

![atom_2017-01-29_12-00-25](https://cloud.githubusercontent.com/assets/1567037/22407405/9cd1209c-e61a-11e6-9ee2-3b34fe7a773b.png)


I'd love to make a matching UI theme someday, but no plans yet. 🙂

**Comment by mikeerickson** [comment]
@nkpfstr Funny, that is what I settled on :-)

**Comment by mikeerickson** [comment]
@nkpfstr It is quite a chore when customizing looking and feel.  I really have new found appreciation for theme / syntax devs.  So, thank you :-)
