### ISSUE TITLE
Light version of this beautiful syntax

### ISSUE THREAD

**Issue by caobo** [polymoon/pure-dark-syntax#2]
Will it be possible?

**Comment by lednhatkhanh** [comment]
+1 for the light variant! It will be awesome!

**Comment by pfist** [comment]
Thanks for the interest! I will explore a light version this weekend. If it works out nicely, I'll publish it and update this issue. 😄

**Comment by DHBuild002** [comment]
Yes Please! 

More yellows and greens. Love the deep purple scheme right now though. Cant Wait to see what you come up with.

How is it going?

**Comment by pfist** [comment]
Hey folks! I finally published a [light version](https://github.com/polymoon/pure-light-syntax)! Hope you like it. Leave an issue over there if you encounter problems or have suggestions for improving it. 😄
