### ISSUE TITLE
Getting "ERR_FILE_NOT_FOUND" in Atom console

### ISSUE THREAD

**Issue by Cthulahoop** [polymoon/pure-dark-syntax#4]
**_System:_**
HW: MacBookPro13,2
OS: macOS 10.12.5 (16F73)

**_Atom version:_**
Atom    : 1.18.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0

**_Issue:_**
On selecting Pure syntax the console generates an error that it can't find the file 
`file:///Applications/Atom.app/Contents/Resources/app/static/syntax/css`

**Comment by pfist** [comment]
@Cthulahoop Are you still getting this error? If so, does it keep Pure Syntax from loading correctly?

**Comment by pfist** [comment]
Since I haven't heard back from you, I'll go ahead and close this issue for now. Let me know if this crops up again.
