### ISSUE TITLE
Functions and class names highlighting

### ISSUE THREAD

**Issue by robahl** [polymoon/pure-dark-syntax#5]
Hi!

I like the Pure syntax theme a lot. But if you compare it to for example "One Dark", functions, class names and plain text all share the same white color highlighting. Wouldn't it help to put one color on function names and another color for class declarations?
![one-dark-pure](https://user-images.githubusercontent.com/979555/30821141-992c9cac-a224-11e7-95f4-77078308a680.png)

**Comment by pfist** [comment]
I agree, and this will be addressed in the next major release. 😄

**Comment by mirelianavioletzyra** [comment]
It's not working for me.

![screen shot 2017-10-11 at 8 40 16 pm](https://user-images.githubusercontent.com/8645004/31473755-73af8168-aec4-11e7-9388-dba4c3a6ab97.png)

**Comment by pfist** [comment]
@moriahcgibbs Could you please open a separate issue and give me some more details? Like which platform you're using, which version of Pure Syntax is installed, etc. Thanks! 🙂
